version: '2'

networks:
  back-tier:
    driver: overlay

services:
  manager:
    image: nohaapav/test-manager
    restart: always
    ports:
      - 80
    networks: 
      - back-tier

  service:
    image: nohaapav/test-service
    restart: always
    ports:
      - 80
    networks:
      - back-tier
